### ISSUE TITLE
Demo 3 issue - Responsive Navigation Bar

### ISSUE THREAD

**Issue by andreaamato-polito** [polito-SE2-TEAM-20/softeng2-Hike-Tracker#36]
Hi, as a user (hiker or local guide) of your application, I would like to have the titles of the navigation bar that adapt according to the different screen dimensions.
Finally, I want to congratulate you on the rich functionality that your application offers.
Thank you.

**Comment by lifeofvins** [comment]
Thank you very much for your feedback, the navbar has been fixed and responsiveness is now provided.
Enjoy the last sprint y'all!

**Comment by lifeofvins** [comment]
Thank you very much for your feedback, the navbar has been fixed and responsiveness is now provided.
Enjoy the last sprint y'all!
