### ISSUE TITLE
Demo 3 issue - Set profile

### ISSUE THREAD

**Issue by fede1997483** [polito-SE2-TEAM-20/softeng2-Hike-Tracker#37]
I want to firstly congratulate with you for the good looking user interface of your application and its usability.
As an hiker, in my profile settings, i would like to be able to define a circular search area on the map instead of inserting the radius in the form manually.
Thank you !

**Comment by lifeofvins** [comment]
Now the radius can be inserted either in the old way (with the textbox) and in the newer one suggested by you, so drawing a circle on the map. Thank you very much for the helpful issue!
