### ISSUE TITLE
[Local Guide POV] Start and End Point

### ISSUE THREAD

**Issue by GigiLoria5** [polito-SE2-TEAM-20/softeng2-Hike-Tracker#4]
As a Local Guide I am disappointed that I can only specify GPS coordinates as the starting and finishing points of the trail I want to propose. I am of course happy to have these coordinates auto-compiled when the gpx file is loaded, but **I expect to be able to specify other types of points as well**, as requested in the initial requirements.

![immagine](https://user-images.githubusercontent.com/41837640/201640377-4258dfe8-b76c-47fe-a9d9-cdd4ecdcd5fa.png)

**Comment by MrR0b0t14** [comment]
You now can specify a label to these points and some other fields auto complete from the gps coordinates (like city, region...).
Thank you very much!
