### ISSUE TITLE
[Hiker POV] Hikes filters

### ISSUE THREAD

**Issue by GigiLoria5** [polito-SE2-TEAM-20/softeng2-Hike-Tracker#5]
As a hiker I am a little frustrated with the way the filters can be applied, I feel that currently the user experience is not the best as the fields are not well organised and that **they should be arranged in some kind of group organisation** (e.g. the first row is for geographical fields, the second for length, etc.). Another thing I found strange is the **lack of predefined selection options**, which I expect especially for geographical and difficulty filters.

**Comment by MrR0b0t14** [comment]
Filters should now be more understandable, thanks a lot!
