### ISSUE TITLE
[Hiker] Ordering of available hikes

### ISSUE THREAD

**Issue by antosams3** [polito-SE2-TEAM-20/softeng2-Hike-Tracker#7]
As an hiker I think that the way to apply ordering of fields on the list of available hikes can be improved by removing the selectors and by just clicking on the name of the field we want to sort by. This allows to have a better user experience and remove useless things from the screen.

**Comment by MrR0b0t14** [comment]
Thank you for your comment, you can now sort clicking on column header!
